services:
  # Backend service
  - type: web
    name: klarisana-form-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  # Frontend service
  - type: web
    name: klarisana-form-frontend
    env: static
    buildCommand: npm install
    startCommand: http-server -p $PORT
    envVars:
      - key: PORT
        value: 8080 